version: '3.4'

services:
  test_nodejs:
    image: test_nodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
